name: spot-client
version: '0.4.0'
summary: Listen to music on Spotify
description: |
  This is an unofficial Snap repackaging of the Spot client for Spotify.

  In order to save your password, the `password-manager-service` plug needs to be manually connected:
     $ snap connect spot-client:password-manager-service

  Listen to music on Spotify.

  Current features:

  - playback control (play/pause, prev/next, seeking)
  - play queue with shuffle option
  - selection mode: easily browse and select mutliple tracks to queue them
  - browse your saved albums and playlists
  - search albums and artists
  - view an artist's releases
  - view users' playlists
  - credentials management with Secret Service
  - MPRIS integration
confinement: strict
base: core22
parts:
  spot:
    source: https://github.com/xou816/spot.git
    source-tag: '0.4.0'
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/snap/spot-client/current/usr
      - -Dbuildtype=release
      - -Doffline=false
    parse-info: [usr/share/metainfo/dev.alextren.Spot.appdata.xml]
    build-snaps:
      - rustup
    override-pull: |
      craftctl default

      sed -i.bak -e 's|Icon=dev.alextren.Spot|Icon=/usr/share/icons/hicolor/scalable/apps/dev.alextren.Spot.svg|g' data/dev.alextren.Spot.desktop
    override-build: |
      rustup default stable
      craftctl default
    prime:
      - -snap/spot-client
    organize:
      snap/spot-client/current: .

apps:
  spot:
    extensions: [gnome]
    command: usr/bin/spot
    desktop: usr/share/applications/dev.alextren.Spot.desktop
    common-id: dev.alextren.Spot.desktop
    plugs: [network, mpris, alsa, audio-playback, wayland, x11, desktop, desktop-legacy, password-manager-service, opengl, gsettings]

slots:
  spot:
    interface: dbus
    bus: session
    name: dev.alextren.Spot
  spot-mpris:
    interface: mpris
    name: Spot